server:
  port: 8083

spring:
  application:
    name: service-passenger-user

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service-passenger-user?characterEncodion=utf-8&serverTimezone=UTC
    username: root
    password: 52yt1314

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

